$('.owl1').owlCarousel({
    loop:true,
    autoplay:true,
    autoplayTimeout:4000,
    responsive:{
        0:{
            items:1
        }
    }
})

$('.owl2').owlCarousel({
    loop:true,
    autoplay:true,
    autoplayTimeout:6500,
    dots:false,
    responsive:{
        0:{
            items:3
        }
    }
})

$('.owl3').owlCarousel({
    loop:true,
    autoplay:true,
    autoplayTimeout:6500,
    dots:false,
    responsive:{
        0:{
            items:1
        }
    }
})